version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    user: postgres
  redis:
    image: redis:6.2.5-alpine
    ports:
    - '6379:6379'
